import React, { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Axios from "axios";

import Card from "../components/LiveCard";

const drawerWidth = 1000;

const Home: NextPage = () => {
  const [rows, setRows] = useState<any | undefined>([]);

  const fetch = () => {
    const dataBox: any[] = [];
    Axios.get("https://schedule.hololive.tv/api/list/7")
      .then((response) => {
        let data = response.data.dateGroupList[0].videoList;
        console.log(data.length);
        console.log(data[0]);
        for (let i = 0; i < data.length; i++) {
          console.log(data[i].name);
          console.log(data[i].talent.iconImageUrl);
          console.log(data[i].title);
          console.log(data[i].thumbtail);
          console.log(data[i].url);
          console.log(data[i].isLive);

          dataBox.push({
            name: data[i].name,
            icon: data[i].talent.iconImageUrl,
            title: data[i].title,
            thumbnail: data[i].thumbtail,
            streamUrl: data[i].url,
            isLive: data[i].isLive,
          });
        }
        setRows(dataBox);
      })
      .catch((error) => {
        console.log(error);
      });
  };

  useEffect(() => {
    fetch();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Root</h1>
        <button onClick={() => fetch()}>fetch</button>
        <Card
        name = {"潤羽るしあ"}
          iconLink = {"http://localhost:3000/_next/image?url=https%3A%2F%2Fyt3.ggpht.com%2Fa%2FAGF-l7-Qgi-J6qJG7c79iMtEveIZIgZVCyltxCh1jA%3Ds88-c-k-c0xffffffff-no-rj-mo&w=128&q=75"}
          title = {"【開封配信】ヴァイスシュヴァルツ！！ホロメンのサインカード当てたい！【潤羽るしあ/ホロライブ】"}
          thumbnailLink = {"https://img.youtube.com/vi/CnqjvPr5GG8/mqdefault.jpg"}
          date = {"2021/10/09 19:03:51"}
        />
      </main>
    </div>
  );
};

export default Home;
